### ISSUE TITLE
This series of articles is really good

### ISSUE THREAD

**Issue by yilezhu** [shahedc/WorkerServiceSample#1]
This series of articles is really good. Can I translate it into Chinese and share it with. net core developers in China?

**Comment by shahedc** [comment]
Hi @yilezhu glad you found it useful! You may translate it into Chinese as long as you provide a link back to my website for the proper credit (for me as the original author) and mention that it's an unofficial translation since I won't be able to verify the translated content for accuracy. 

Since it's a free ebook, you may not sell it or profit from it in any way. 

Thanks!

**Comment by yilezhu** [comment]
I known,I just want to contribute to the. net community in China.
